Repository KratosMultiphysics/CoSimIO, pull requests merged in 2020-06, with the labels that each got.

#64 modularize py-exposure
  co_sim_io/python/co_sim_io_python.cpp
  co_sim_io/python/connection_status_to_python.hpp
  co_sim_io/python/info_to_python.hpp
  co_sim_io/python/version_to_python.hpp
Labels: interface Python

#66 Fix c import mesh
  co_sim_io/c/co_sim_io_c.cpp
  tests/integration_tutorials/c/import_mesh.c
Labels: bug, interface C

#67 Suggestions for tutorial
  tutorial/c/README.md
Labels: documentation

#68 Add tutorials for kratos connection
  tests/integration_tutorials/c/export_import_data.c
  tests/integration_tutorials/c/export_import_mesh.c
  tests/integration_tutorials/c/import_mesh.c
  tutorial/README.md
  tutorial/c/README.md
Labels: documentation, interface C
