Repository KratosMultiphysics/CoSimIO, pull requests merged in 2023-10, with the labels that each got.

#361 [Scripts] Adding Windows scripts
  scripts/build.bat
  scripts/build_and_test.bat
  scripts/build_c.bat
  scripts/build_cpp.bat
  scripts/build_python.bat
Labels: bugfix, windows, usability

#362 [Documentation] Update documentation for CoSimIO integration in C++, C, and Python for Windows
  docs/tutorials/c/integration_co_sim_io.md
  docs/tutorials/cpp/integration_co_sim_io.md
  docs/tutorials/python/integration_co_sim_io.md
Labels: documentation, windows

#363 Initial support LLVM Intel in Windows
  co_sim_io/includes/communication/pipe_communication.hpp
  co_sim_io/sources/communication/pipe_communication.cpp
  scripts/build.bat
Labels: windows

#364 Adding ICX in CI
  .github/workflows/ci.yml
Labels: continuous integration
